baseURL = 'https://pjpark.com.br/'
languageCode = 'pt-br'
title = 'PJ Park'

DefaultContentLanguage = "pt-br"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
ignoreErrors = ["error-remote-getjson"]

[params]
title = "PJ Park"
description = "O primeiro escritório online especializado em empresas inativas. Apenas R$ 59,90 mensais."
mainSections = ["blog"]

[menu]

  [[menu.main]]
  name = "Serviços adicionais"
  identifier = "servicos"
  weight = 10
  url = "/servicos"

  [[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
